### ISSUE TITLE
Retrieve created resource meta data at runtime 

### ISSUE THREAD

**Issue by raksiv** [nitrictech/nitric#301]
**Describe the solution you'd like**

Would like to be able to retrieve meta information about a resource so that it can be used by other services.
This should apply to all resources e.g. buckets, topics, api gateways...

E.g. Knowing the API gateway URL during runtime would make it easier to integrate with 3rd party integrations for a callback
Knowing the S3 bucket creation name, would allow us to use tools like Rekognition directly from an S3 bucket  

**Why is this needed? What challenge will it help you solve? Please describe.**

For 3rd party integrations and managed service usage

**Describe alternatives you've considered**

Environment variables which store references to created resources 
- not ideal as it requires manual management 

Constructing the URL or resource name out of known details
- Not ideal as it isn't always possible, especially when an ID is auto-generated. 

- [ ] [Retreive meta data about Events](https://github.com/nitrictech/nitric/issues/305)
- [ ] Retreive meta data for Queues
- [x] Retreive meta data for Buckets
- [ ] Retreive meta data for API Gateways
- [ ] Retreive meta data for Secrets
- [ ] Retreive meta data for Collections

**Comment by tjholm** [comment]
@raksiv we'll probably want to break this down into multiple tasks
